# Generated by Django 4.2.7 on 2025-08-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcasts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('audio_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('play_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcast')),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('podcast', 'slug')},
            },
        ),
    ]
