# Generated by Django 4.2.7 on 2025-10-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_alter_episode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='ad_free_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='ad_supported_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]

