# Generated by Django 4.2.7 on 2025-10-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_dual_audio_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='ad_free_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ad_supported_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_url',
            field=models.TextField(),
        ),
    ]
