# Generated by Django 4.2.7 on 2025-10-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_alter_episode_ad_free_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
