# Generated by Django 4.2.7 on 2025-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0005_alter_episode_slug_alter_episode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='cover_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
