# Generated by Django 4.2.7 on 2025-10-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
    ]
