# Generated by Django 4.2.7 on 2025-10-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_remove_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
