# Generated by Django 4.2.7 on 2025-10-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_alter_creator_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
