# Generated by Django 4.2.7 on 2026-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
