# Generated by Django 4.2.7 on 2026-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_imported_from_memberful',
            field=models.BooleanField(default=False),
        ),
    ]
