# Generated by Django 4.2.7 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_email_verified_and_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_email_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
