# Generated by Django 5.2 on 2026-04-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_pending_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_mature_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
