# Generated by Django 4.2.7 on 2026-04-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memberful_plan_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
