# Generated by Django 5.2 on 2026-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_memberful_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_trial_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_legacy_free_trial',
            field=models.BooleanField(default=False),
        ),
    ]
