# Generated by Django 4.2.7 on 2025-10-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('cover_image', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_episodes', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='creators.creator')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=500, unique=True)),
                ('variant', models.CharField(choices=[('ad_supported', 'Ad-Supported'), ('ad_free', 'Ad-Free')], default='ad_supported', max_length=20)),
                ('language', models.CharField(blank=True, help_text='Override language on Podcast', max_length=10, null=True)),
                ('update_only', models.BooleanField(default=False, help_text='If true, do not create Podcast if missing')),
                ('limit', models.IntegerField(blank=True, help_text='Process only first N entries (testing)', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('etag', models.CharField(blank=True, max_length=200, null=True)),
                ('last_modified', models.CharField(blank=True, max_length=200, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('creator', models.ForeignKey(blank=True, help_text='Used when creating a Podcast if not already linked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='creators.creator')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_sources', to='podcasts.podcast')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
