# Generated by Django 4.2.7 on 2025-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='etag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedsource',
            name='last_modified',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.TextField(),
        ),
    ]
