# Generated by Django 4.2.7 on 2025-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_alter_feedsource_etag_alter_feedsource_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.TextField(),
        ),
    ]
