# Generated by Django 4.2.7 on 2025-10-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('podcasts', '0003_alter_podcast_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='category',
        ),
        migrations.AddField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='podcasts', to='categories.category'),
        ),
    ]
