"""
Django settings for EeriecastDjango project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Replace hard-coded secret with env-based, fallback to the existing value for local/dev
SECRET_KEY = config('SECRET_KEY', default='django-insecure-sf%hq^q4t1mpwu^yn6zrwa&r$3e-$8q0)o8zr&!c7lt30183un')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=True)

# Allow overriding via env for production; fallback to wildcard
ALLOWED_HOSTS = [h for h in config('ALLOWED_HOSTS', default='*').split(',') if h]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DJANGO_CORS_OVERRIDE = True
#DJANGO_CORS_OVERRIDE = config('DJANGO_CORS_OVERRIDE', cast=bool)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.common.authentication.LenientJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Changed from IsAuthenticated to allow public access by default
    ],
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.OrderingFilter',
    ],
    'COERCE_DECIMAL_TO_STRING': False,
}

REACT_BASE_URL = 'http://localhost:3000'

UNFOLD = {
    "SITE_HEADER": "Eeriecast Admin",
    "SITE_TITLE": "Eeriecast Admin Portal",
    "COLORS": {
        "base": {
            "50":  "250, 250, 250",    # very light gray
            "100": "240, 240, 240",    # light gray
            "200": "220, 220, 220",    # medium light gray
            "300": "180, 180, 180",    # medium gray
            "400": "140, 140, 140",    # dark gray
            "500": "100, 100, 100",    # darker gray
            "600": "80, 80, 80",       # very dark gray
            "700": "60, 60, 60",       # almost black
            "800": "40, 40, 40",       # very dark
            "900": "20, 20, 20",       # near black
            "950": "0, 0, 0",          # pure black
        },
        "primary": {
            "50":  "255, 248, 235",    # very light gold
            "100": "255, 243, 213",    # light gold
            "200": "255, 235, 181",    # medium light gold
            "300": "255, 220, 133",    # medium gold
            "400": "255, 200, 87",     # gold
            "500": "255, 193, 7",      # bright gold (main color)
            "600": "239, 68, 68",      # red accent
            "700": "220, 38, 127",     # darker red
            "800": "185, 28, 28",      # dark red
            "900": "153, 27, 27",      # very dark red
            "950": "127, 29, 29",      # deepest red
        },
        "font": {
            # for light theme, use black text on light backgrounds
            "default-light": "#000000",


            # subtle colors - gray for light, gold for dark
            "subtle-light": "var(--color-base-500)",
            "subtle-dark":  "#FFC107",

            # important text - black for light, bright gold for dark
            "important-light": "#000000",
            "important-dark":  "#FFD700",
        },
    },
}



# DEFAULT_FROM_EMAIL = 'ConciergeFirst <info@nimbuseditor.com>'

if DEBUG:
    CORS_ORIGIN_ALLOW_ALL = True
else:
    if not DJANGO_CORS_OVERRIDE:
        CORS_ORIGIN_WHITELIST = [
            # TODO: add to whitelist
        ]
    else:
        CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'apps.authentication',
    'apps.podcasts',
    'apps.episodes',
    'apps.creators',
    'apps.categories',
    'apps.library',
    'apps.search',
    'apps.common',
    'apps.billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'EeriecastDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EeriecastDjango.wsgi.application'

AUTH_USER_MODEL = "authentication.User"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# Ensure collectstatic has a target in Docker builds
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use compressed manifest storage in production for optimal caching
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Optional media settings (adjust as needed)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security and proxy settings for production behind Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Provide CSRF trusted origins via environment (comma-separated, include scheme)
_CSRF_TRUSTED = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _CSRF_TRUSTED:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _CSRF_TRUSTED.split(',') if o.strip()]

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",  # Vite default
]

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Environment variables
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'
# Stripe
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_MONTHLY_PRICE_ID = os.getenv('STRIPE_MONTHLY_PRICE_ID', 'price_1QVkCFDZQqr6bWze584rDEz0')
STRIPE_TRIAL_DAYS = 7

DATA_UPLOAD_MAX_NUMBER_FIELDS = 9999999

# Celery configuration
# Broker/Backend default to Redis container in docker-compose
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery beat schedule - run daily at 03:00 UTC
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'sync-all-feeds-daily': {
        'task': 'podcasts.sync_all_feeds',
        'schedule': crontab(hour=3, minute=0),
        'options': {'time_limit': 60 * 60},  # 1 hour time limit safety
    },
}

# Logging configuration to surface info in Docker logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'podcasts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
