# Generated by Django 4.2.7 on 2026-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="email_backend",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_host_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_use_tls",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="email_use_ssl",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
