# Generated by Django 4.2.7 on 2026-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_emailevent_server_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="email_host_password",
            field=models.TextField(blank=True, default=""),
        ),
    ]
