# Generated by Django 4.2.7 on 2026-02-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_emailevent_email_host_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailevent",
            name="email_host_password",
        ),
    ]
