# Generated by Django 4.2.7 on 2026-02-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_emailevent_email_host_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('args', models.JSONField(blank=True, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Celery Task Log',
                'verbose_name_plural': 'Celery Task Logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
