# Generated by Django 4.2.7 on 2026-02-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_celerytasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasklog',
            name='worker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
